"""02_tasks_projects

Revision ID: 79263d5a80fb
Revises: 144f954490e7
Create Date: 2026-04-19 08:24:33.939739

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "79263d5a80fb"
down_revision: Union[str, Sequence[str], None] = "144f954490e7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tf_projects',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=255), nullable=False),
                    sa.Column('description', sa.Text(), nullable=True),
                    sa.Column('creator_id', sa.Integer(), nullable=False),
                    sa.Column('project_type', sa.String(length=50), nullable=True),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.ForeignKeyConstraint(['creator_id'], ['tf_users.id'], )
                    )
    op.create_index(op.f('ix_tf_projects_name'), 'tf_projects', ['name'], unique=False)

    # Tasks table
    op.create_table('tf_tasks',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=255), nullable=False),
                    sa.Column('description', sa.Text(), nullable=True),
                    sa.Column('project_id', sa.Integer(), nullable=False),
                    sa.Column('status', sa.String(length=50), nullable=False),
                    sa.Column('priority', sa.String(length=50), nullable=True),
                    sa.Column('assignee_id', sa.Integer(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('estimated_hours', sa.Float(), nullable=True),
                    sa.Column('spent_hours', sa.Float(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.ForeignKeyConstraint(['assignee_id'], ['tf_users.id'], ),
                    sa.ForeignKeyConstraint(['project_id'], ['tf_projects.id'], )
                    )
    op.create_index(op.f('ix_tf_tasks_status'), 'tf_tasks', ['status'], unique=False)
    # ### end Alembic commands ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tf_tasks_status'), table_name='tf_tasks')
    op.drop_table('tf_tasks')
    op.drop_index(op.f('ix_tf_projects_name'), table_name='tf_projects')
    op.drop_table('tf_projects')
    # ### end Alembic commands ###
