"""Fixes

Revision ID: 40c91e15b21e
Revises: 531d13d60870
Create Date: 2026-05-17 23:19:52.732468

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "40c91e15b21e"
down_revision: Union[str, Sequence[str], None] = "531d13d60870"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tf_tasks",
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
    )
    op.add_column(
        "tf_projects",
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
    )
    op.create_index(
        op.f("ix_tf_tasks_creator_id"),
        "tf_tasks",
        ["creator_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tf_tasks_creator_id"), table_name="tf_tasks")
    op.drop_column("tf_tasks", "updated_at")
    op.drop_column("tf_projects", "updated_at")
    # ### end Alembic commands ###
