"""projects_tasks

Revision ID: 927a74cd75b0
Revises: 144f954490e7
Create Date: 2026-04-19 11:01:05.029451

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "927a74cd75b0"
down_revision: Union[str, Sequence[str], None] = "144f954490e7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tf_projects",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), server_default="", nullable=False),
        sa.Column("description", sa.Text(), server_default="", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("TIMEZONE('utc', now())"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("TIMEZONE('utc', now())"),
            nullable=False,
        ),
        sa.Column("creator_id", sa.Integer(), nullable=False),
        sa.Column(
            "project_type",
            sa.Enum(
                "software",
                "business",
                "service_desk",
                name="project_type_enum",
                inherit_schema=True,
            ),
            nullable=False,
        ),
        sa.CheckConstraint(
            "length(description) <= 1000",
            name="project_description_max_length",
        ),
        sa.CheckConstraint(
            "length(name) <= 100", name="project_name_max_length"
        ),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            ["tf_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_tf_projects_creator_id"),
        "tf_projects",
        ["creator_id"],
        unique=False,
    )
    op.create_index(
        "ix_tf_projects_project_type",
        "tf_projects",
        ["project_type"],
        unique=False,
    )
    op.create_table(
        "tf_tasks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), server_default="", nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("project_id", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "todo",
                "in_progress",
                "review",
                "done",
                name="task_status_enum",
                inherit_schema=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "priority",
            sa.Enum(
                "low",
                "medium",
                "high",
                "critical",
                name="task_priority_enum",
                inherit_schema=True,
            ),
            nullable=False,
        ),
        sa.Column("due_date", sa.DateTime(), nullable=True),
        sa.Column("creator_id", sa.Integer(), nullable=False),
        sa.Column("assignee_id", sa.Integer(), nullable=True),
        sa.Column("time_estimate", sa.Integer(), nullable=True),
        sa.Column("time_spent", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("TIMEZONE('utc', now())"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("TIMEZONE('utc', now())"),
            nullable=False,
        ),
        sa.CheckConstraint("length(name) <= 255", name="task_name_max_length"),
        sa.ForeignKeyConstraint(
            ["assignee_id"],
            ["tf_users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            ["tf_users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["tf_projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_tf_tasks_assignee_id"),
        "tf_tasks",
        ["assignee_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tf_tasks_creator_id"),
        "tf_tasks",
        ["creator_id"],
        unique=False,
    )
    op.create_index(
        "ix_tf_tasks_priority", "tf_tasks", ["priority"], unique=False
    )
    op.create_index(
        "ix_tf_tasks_project_id", "tf_tasks", ["project_id"], unique=False
    )
    op.create_index("ix_tf_tasks_status", "tf_tasks", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_tf_tasks_status", table_name="tf_tasks")
    op.drop_index("ix_tf_tasks_project_id", table_name="tf_tasks")
    op.drop_index("ix_tf_tasks_priority", table_name="tf_tasks")
    op.drop_index(op.f("ix_tf_tasks_creator_id"), table_name="tf_tasks")
    op.drop_index(op.f("ix_tf_tasks_assignee_id"), table_name="tf_tasks")
    op.drop_table("tf_tasks")
    op.drop_index("ix_tf_projects_project_type", table_name="tf_projects")
    op.drop_index(op.f("ix_tf_projects_creator_id"), table_name="tf_projects")
    op.drop_table("tf_projects")
    # ### end Alembic commands ###
