"""redesign user table

Revision ID: a55fa878c4dd
Revises: 927a74cd75b0
Create Date: 2026-05-08 16:26:50.285300

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a55fa878c4dd"
down_revision: Union[str, Sequence[str], None] = "cb42e228ad53"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.drop_index(op.f("ix_tf_tasks_creator_id"), table_name="tf_tasks")
    op.add_column(
        "tf_users",
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
    )
    op.add_column(
        "tf_users", sa.Column("is_superuser", sa.Boolean(), nullable=False)
    )
    op.add_column(
        "tf_users", sa.Column("is_verified", sa.Boolean(), nullable=False)
    )
    op.alter_column(
        "tf_users",
        "email",
        existing_type=sa.TEXT(),
        type_=sa.String(length=320),
        existing_nullable=False,
    )
    op.alter_column(
        "tf_users",
        "hashed_password",
        existing_type=sa.TEXT(),
        type_=sa.String(length=1024),
        existing_nullable=False,
    )
    op.create_index(
        op.f("ix_tf_users_email"), "tf_users", ["email"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tf_users_email"), table_name="tf_users")
    op.alter_column(
        "tf_users",
        "hashed_password",
        existing_type=sa.String(length=1024),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.alter_column(
        "tf_users",
        "email",
        existing_type=sa.String(length=320),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.drop_column("tf_users", "is_verified")
    op.drop_column("tf_users", "is_superuser")
    op.drop_column("tf_users", "updated_at")
    op.create_index(
        op.f("ix_tf_tasks_creator_id"),
        "tf_tasks",
        ["creator_id"],
        unique=False,
    )
   