"""empty message

Revision ID: cb42e228ad53
Revises: 144f954490e7
Create Date: 2026-05-05 06:22:52.867072

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "cb42e228ad53"
down_revision: Union[str, Sequence[str], None] = "144f954490e7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tf_users",
        sa.Column("fullname", sa.Text(), server_default="", nullable=False),
        sa.Column("username", sa.Text(), nullable=False),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column("hashed_password", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.CheckConstraint("length(email) <= 50", name="email_max_length"),
        sa.CheckConstraint(
            "length(fullname) <= 100", name="full_name_max_length"
        ),
        sa.CheckConstraint(
            "length(username) <= 32", name="username_max_length"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "tf_projects",
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("creator_id", sa.Integer(), nullable=False),
        sa.Column(
            "project_type",
            sa.Enum(
                "software",
                "business",
                "service_desk",
                name="project_type_enum",
                inherit_schema=True,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "length('description') <= 1000",
            name="project_description_max_length",
        ),
        sa.CheckConstraint(
            "length('name') <= 100", name="project_name_max_length"
        ),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            ["tf_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(
        op.f("ix_tf_projects_creator_id"),
        "tf_projects",
        ["creator_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tf_projects_project_type"),
        "tf_projects",
        ["project_type"],
        unique=False,
    )
    op.create_table(
        "tf_tasks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("project_id", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "todo",
                "in_progress",
                "done",
                name="task_status_enum",
                inherit_schema=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "priority",
            sa.Enum(
                "low",
                "medium",
                "high",
                name="task_priority_enum",
                inherit_schema=True,
            ),
            nullable=False,
        ),
        sa.Column("due_date", sa.DateTime(), nullable=True),
        sa.Column("creator_id", sa.Integer(), nullable=False),
        sa.Column("assignee_id", sa.Integer(), nullable=True),
        sa.Column("time_estimate", sa.Integer(), nullable=True),
        sa.Column("time_spent", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("length(name) <= 255", name="task_name_max_length"),
        sa.ForeignKeyConstraint(
            ["assignee_id"],
            ["tf_users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            ["tf_users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["tf_projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_tf_tasks_assignee_id"),
        "tf_tasks",
        ["assignee_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tf_tasks_creator_id"),
        "tf_tasks",
        ["creator_id"],
        unique=False,
    )
    op.create_index(op.f("ix_tf_tasks_id"), "tf_tasks", ["id"], unique=False)
    op.create_index(
        op.f("ix_tf_tasks_name"), "tf_tasks", ["name"], unique=False
    )
    op.create_index(
        op.f("ix_tf_tasks_priority"), "tf_tasks", ["priority"], unique=False
    )
    op.create_index(
        op.f("ix_tf_tasks_project_id"),
        "tf_tasks",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tf_tasks_status"), "tf_tasks", ["status"], unique=False
    )
    op.create_table(
        "tf_user_project",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["tf_projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["tf_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tf_user_project")
    op.drop_index(op.f("ix_tf_tasks_status"), table_name="tf_tasks")
    op.drop_index(op.f("ix_tf_tasks_project_id"), table_name="tf_tasks")
    op.drop_index(op.f("ix_tf_tasks_priority"), table_name="tf_tasks")
    op.drop_index(op.f("ix_tf_tasks_name"), table_name="tf_tasks")
    op.drop_index(op.f("ix_tf_tasks_id"), table_name="tf_tasks")
    op.drop_index(op.f("ix_tf_tasks_creator_id"), table_name="tf_tasks")
    op.drop_index(op.f("ix_tf_tasks_assignee_id"), table_name="tf_tasks")
    op.drop_table("tf_tasks")
    op.drop_index(
        op.f("ix_tf_projects_project_type"), table_name="tf_projects"
    )
    op.drop_index(op.f("ix_tf_projects_creator_id"), table_name="tf_projects")
    op.drop_table("tf_projects")
    op.drop_table("tf_users")
    # ### end Alembic commands ###
