"""empty message

Revision ID: ff08369c7483
Revises: 927a74cd75b0
Create Date: 2026-05-04 07:05:15.244366

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ff08369c7483"
down_revision: Union[str, Sequence[str], None] = "927a74cd75b0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "tf_projects",
        "description",
        existing_type=sa.TEXT(),
        nullable=True,
        existing_server_default=sa.text("''::text"),
    )
    op.create_unique_constraint(None, "tf_projects", ["name"])
    op.drop_column("tf_projects", "updated_at")
    op.alter_column(
        "tf_tasks",
        "name",
        existing_type=sa.TEXT(),
        type_=sa.String(length=255),
        existing_nullable=False,
        existing_server_default=sa.text("''::text"),
    )
    op.create_index(op.f("ix_tf_tasks_id"), "tf_tasks", ["id"], unique=False)
    op.create_index(
        op.f("ix_tf_tasks_name"), "tf_tasks", ["name"], unique=False
    )
    op.drop_column("tf_tasks", "updated_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tf_tasks",
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("timezone('utc'::text, now())"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_index(op.f("ix_tf_tasks_name"), table_name="tf_tasks")
    op.drop_index(op.f("ix_tf_tasks_id"), table_name="tf_tasks")
    op.alter_column(
        "tf_tasks",
        "name",
        existing_type=sa.String(length=255),
        type_=sa.TEXT(),
        existing_nullable=False,
        existing_server_default=sa.text("''::text"),
    )
    op.add_column(
        "tf_projects",
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("timezone('utc'::text, now())"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint(None, "tf_projects", type_="unique")
    op.alter_column(
        "tf_projects",
        "description",
        existing_type=sa.TEXT(),
        nullable=False,
        existing_server_default=sa.text("''::text"),
    )
    # ### end Alembic commands ###
